parameters:
  - name: androidVersion
    type: string

jobs:
  - job: AndroidTests${{ parameters.androidVersion }}
    displayName: Android Tests (v${{ parameters.androidVersion }})
    variables:
      ports:
      #ports: 5554 5556

    steps:

      - template: step-cache-gradle-files.yml

      - task: Gradle@2
        displayName: Build APKs
        inputs:
          tasks: 'assembleAndroidTest'
          gradleWrapperFile: 'gradlew'

      - task: Bash@3
        displayName: Create Emulator
        inputs:
          targetType: inline
          script: ./azure/emulator-create.sh ${{ parameters.androidVersion }} $(ports)

      - task: Bash@3
        displayName: Start Emulator
        inputs:
          targetType: inline
          script: |
            ./azure/emulator-start-on-ci.sh $(ports)
            ./azure/emulator-wait.sh $(ports)
            ./azure/emulator-optimize.sh $(ports)
            ./azure/emulator-collect-preconditions.sh $(ports)
            ./azure/emulator-collect-logcat.sh $(ports)

      - task: PublishPipelineArtifact@1
        displayName: Publish Emulator Settings
        inputs:
          targetPath: emulator-settings
          artifactName: Emulator ${{ parameters.androidVersion }} Settings
        condition: succeededOrFailed()

      - task: Bash@3
        displayName: Test on Emulator
        inputs:
          targetType: inline
          script: |
            # Task should fail if any bash command fail. Through pipelines the previus command result is by default ignored.
            set -o pipefail
            # Print info about test execution to have some ongoing feedback. Must be done in the same task where we want the output.
            ./azure/emulator-print-test-execution.sh $(ports)
            # Start test run
            ./azure/emulator-run-tests-parallel.sh $(ports)

      - task: PublishTestResults@2
        displayName: Publish Test Results
        inputs:
          testRunTitle: UI Tests Results ${{ parameters.androidVersion }}
          mergeTestResults: true
        condition: succeededOrFailed()

      - task: Bash@3
        displayName: Prepare Emulator Screenshots
        inputs:
          targetType: inline
          script: |
            mkdir emulator-screenshots
            find */build -name screenshots.zip
            find */build -name screenshots.zip -exec unzip "{}" -d emulator-screenshots \;

            #for PORT in $(ports); do
            #    ls */build/outputs/connected_android_test_additional_output/debugAndroidTest/connected/android-ci-$PORT*/screenshots.zip
            #    unzip "*/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected/android-ci-$PORT*/screenshots.zip" -d emulator-screenshots/
            #done
        condition: succeededOrFailed()

      - template: step-publish-emulator-artifacts.yml
        parameters:
          androidVersion: ${{ parameters.androidVersion }}
      - template: step-cache-gradle-files-post.yml