pool:
  # 10.15 has issues with slow emulator, error is:
  # Unable to create basic Accelerated OpenGL renderer.
  # Unable to create basic Accelerated OpenGL renderer.
  # Core Image is now using the software OpenGL renderer. This will be slow.
  vmImage: 'macOS-10.14'

jobs:

  - template: job-android-tests.yml
    parameters:
      # earliest supported android version
      androidVersion: '16'

  - template: job-android-tests.yml
    parameters:
      # earliest supported android version by ui automator (e.g. take screenshots)
      androidVersion: '18'

  - template: job-android-tests.yml
    parameters:
      # fastest android version for emulator ??
      androidVersion: '24'

  - template: job-android-tests.yml
    parameters:
      # latest supported android version
      androidVersion: '30'