jobs:
  - job: earliestVersion
    displayName: 'test supported android version (earliest)'
    pool:
      vmImage: 'macOS-10.15'
    variables:
      IS_CI_ENVIRONMENT: true
    steps:
      - template: templates/supported-android-version.yml
        parameters:
          androidVersion: 'android-18'

  - job: latestVersion
    displayName: 'test supported android version (latest)'
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/supported-android-version.yml
        parameters:
          androidVersion: 'android-29'

  - job: version21
    displayName: 'test supported android version (latest)'
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/supported-android-version.yml
        parameters:
          androidVersion: 'android-21'

  - job: version22
    displayName: 'test supported android version (latest)'
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/supported-android-version.yml
        parameters:
          androidVersion: 'android-22'

  - job: version23
    displayName: 'test supported android version (latest)'
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/supported-android-version.yml
        parameters:
          androidVersion: 'android-23'

  - job: version24
    displayName: 'test supported android version (latest)'
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/supported-android-version.yml
        parameters:
          androidVersion: 'android-24'

  - job: version25
    displayName: 'test supported android version (latest)'
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/supported-android-version.yml
        parameters:
          androidVersion: 'android-25'

  - job: version26
    displayName: 'test supported android version (latest)'
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/supported-android-version.yml
        parameters:
          androidVersion: 'android-26'

  - job: version27
    displayName: 'test supported android version (latest)'
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/supported-android-version.yml
        parameters:
          androidVersion: 'android-27'

  - job: version28
    displayName: 'test supported android version (latest)'
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/supported-android-version.yml
        parameters:
          androidVersion: 'android-28'
