jobs:
  - job: test supported android version (earliest)
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/supported-android-version.yml
        parameters:
          androidVersion: 'android-18'

  - job: test supported android version (latest)
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/supported-android-version.yml
        parameters:
          androidVersion: 'android-29'